### ISSUE TITLE
ARM docker image

### ISSUE THREAD

**Issue by rursache** [activecs/docker-cron-restart-notifier#12]
Please create a ARM docker image

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by activecs** [comment]
@rursache I've just pushed linux/arm64/v7 and linux/arm64 images but I don't have arm machine to verify. Could you check one more time?

**Comment by rursache** [comment]
> @rursache I've just pushed linux/arm64/v7 and linux/arm64 images but I don't have arm machine to verify. Could you check one more time?

thank you, will test in a few minutes
