### ISSUE TITLE
Incorrect Discord regular expression

### ISSUE THREAD

**Issue by brum74** [activecs/docker-cron-restart-notifier#30]
I just created a new Discord webhook to tryout with this container and it contains a dash "-" in the token portion which fails the validation check.  I tried finding documentation on what is considered valid characters for the token but didn't find much.

https://github.com/activecs/docker-cron-restart-notifier/blob/53206a571ab2162ef2a707049b021253e4a023dd/notifier-app/discordNotification.js#L10

Using [\w-]+ in replace for \w+ should resolve the issue.

**Comment by activecs** [comment]
hi @brum74 thanks, I'll update the regexp

**Comment by activecs** [comment]
@brum74 regexp is updated, could you pull the latest image and check if it fine?

**Comment by brum74** [comment]
@activecs looks good
