### ISSUE TITLE
Container Not Restarting

### ISSUE THREAD

**Issue by HinksUK** [activecs/docker-cron-restart-notifier#49]
I can see the notification in Discord but the container did not restart.

"The next scheduled (jmusicbot) container restart is set for 9/10/2024, 9:45:00 AM.
Container Restart Scheduler"

Not sure if this is defaulting to 30 days or whether date format is in the US format? If so, how do I switch to daily?

My stack is below:

services:
  restart-notifier:
    container_name: restart-notifier
    image: index.docker.io/deduard/tools:restart-notifier-latest
    restart: unless-stopped
    environment:
      DISCORD_WEBHOOK_URL: REDACTED
      RESTART_CONTAINERS: "jmusicbot"
      RUN_ON_STARTUP: "false"
      TIMEZONE: Europe/London
      CRON_SCHEDULE: "45 9 * * *" # Every Day at 09:30
      CYCLE_PERIOD: "10000" # 10 sec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by activecs** [comment]
hi @HinksUK, did you solve the issue? what was the cause?

**Comment by HinksUK** [comment]
Yeah I did thanks. Think I was just being a bit impatient. The notification finally came through a minute or so after the time.
